spring:
  application:
    name: authService

  datasource:
    url: jdbc:mysql://localhost:3307/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: lsy749200!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

jwt:
  secret: your-very-secure-and-long-secret-key-for-jwt-at-least-32-chars-long # 실제로는 32바이트 이상의 복잡한 무작위 문자열 사용 권장
  expiration_time: 1800000